version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgresql
    env_file:
      - .env-prod

  redis:
    image: redis:7
    container_name: redis

  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: money_tracker_app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis