version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgresql
    env_file:
      - .env-prod
    ports:
      - 1111:5432

  alembic:
    build:
      context: ./alembic
    env_file:
      - ./alembic/.env-prod
    container_name: alembic
    tty: true

  redis:
    image: redis:7
    container_name: redis

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 8000:8000

  auth_service:
    build:
      context: ./auth
    env_file:
      - ./auth/.env-prod
    container_name: auth_service
    ports:
      - 8002:8002

  tracker_service:
    build:
      context: ./tracker
    env_file:
      - ./tracker/.env-prod
    container_name: tracker_service
    ports:
      - 8003:8003

  news_service:
    build:
      context: ./news
    env_file:
      - ./news/.env-prod
    container_name: news_service
    ports:
      - 8001:8001